# Generated by Django 5.0.4 on 2024-05-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_Salas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='cantidad_computadoras',
            field=models.IntegerField(default=0),
        ),
    ]
